openapi: 3.0.2
info:
  version: "1.0.3"
  title: "Scada Web API"
  description: "Scada Web API"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: https://mock.apidog.com/m1/606880-573224-default
    description: Mock API
  - url: https://api-dev.oosa.life 
    description: Dev API


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT