openapi: 3.0.0
info:
  version: 1.0.0
  title: Event_Service
  description: 事件管理相關服務

paths:
  /v2/event:
    get:
      tags: [event]
      summary: 取得事件清單
      operationId: get-event
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: type
          required: true
          schema:
            type: string
            enum: ["auth_login", "user_control", "avg_persistence", "elec_demand_setting","elec_demand_control", "queue_setting","queue_control", "schedule_setting", "schedule_control"]
          description: 類型
        - in: query
          name: start
          required: false
          schema:
            type: string
          description: 日期 (2016-07-14T00:00:00Z)
          example: "2016-07-14T00:00:00Z"
        - in: query
          name: end
          required: false
          schema:
            type: string
          description: 日期 (2016-07-14T00:00:00Z)
          example: "2016-07-14T00:00:00Z"
        - in: query
          name: interval
          required: false
          schema:
            type: string
            enum: ["1h, 2h, 4h, 6h, 12h, 24h"]
          description: 依現在時間前 x 小時
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetEventList'
        '204':
          description: no content
        '403':
          description: alert config disable
        '500':
          description: 伺服器發生錯誤
  /v2/warning/realtime:
    get:
      tags: [ews]
      summary: 取得即時預警清單
      operationId: get-warning-realtime
      security:
        - bearerAuth: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetWarningRealtime'
              examples:
                objectExample:
                  $ref: '#/components/examples/WarningRealtimeExample'
        '204':
          description: no content
        '401':
          description: permission denied
        '500':
          description: 伺服器發生錯誤
  /v2/warning/realtime/confirmation:
    post:
      tags: [ews]
      summary: 即時告警確認
      operationId: realtime-warning-confirmation
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: OK
        '400':
          description: Invalid Input
        '401':
          description: permission denied
  /v2/warning:
    get:
      tags: [ews]
      summary: 取得歷史預警清單
      operationId: get-warning
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: field
          required: false
          schema:
            type: string
          description: 欄位 (未指定時為所有欄位)
          example: "fieldA%2BfieldB"
        - in: query
          name: type
          required: false
          schema:
            type: string
            enum: ["rubase-alert", "alarm", "com2scada"]
          description: 類型 (預警、告警、欄位斷線)
        - in: query
          name: start
          required: false
          schema:
            type: string
          description: 日期 (2016-07-14T00:00:00Z)
          example: "2016-07-14T00:00:00Z"
        - in: query
          name: end
          required: false
          schema:
            type: string
          description: 日期 (2016-07-14T00:00:00Z)
          example: "2016-07-14T00:00:00Z"
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetWarning'
              examples:
                objectExample:
                  $ref: '#/components/examples/WarningListExample'
        '204':
          description: no content
        '401':
          description: permission denied
components:
  schemas:
    fieldInfo:
      type: object
      properties:
        field:
          type: string
        name:
          type: string
    logical:
      type: object
      properties:
        op:
          type: string
          enum: ['=', '!=', '>', '<', '>=', '<=', '&=']
        value:
          type: number
    condition:
      type: object
      properties:
        enable:
          type: boolean
        time_range:
          type: object
          properties:
            start:
              type: string
              example: "00:00:00Z"
            end:
              type: string
              example: "23:59:59Z"
        week_days:
          type: array
          items:
            type: integer
        frequency:
          type: object
          properties:
            minutes:
              type: integer
            times:
              type: integer
        logicals:
          type: array
          items:
            $ref: '#/components/schemas/logical'
    GetEventList:
      properties:
        time:
          type: string
        service:
          type: string
        type:
          type: string
        summarize:
          type: string
        detail:
          type: string
    GetWarningRealtime:
      type: object
      properties:
        key:
          type: string
        time:
          type: string
        name:
          type: string
          description: 預警名稱
        type:
          type: string
        field_info:
          $ref: '#/components/schemas/fieldInfo'
        detail:
          type: object
          description: 依照不同類型會有不同的欄位
          properties:
            condition:
              $ref: '#/components/schemas/condition'
        is_viewed:
          type: boolean
        view_logs:
          type: array
          items:
            type: object
            properties:
              time:
                type: string
              account:
                type: string
    rubaseDetail:
      type: object
      properties:
        condition:
              $ref: '#/components/schemas/condition'
    alarmDetail:
      type: object
      properties:
        error_msg:
          type: string
    emptyDetail:
      type: object
    GetWarning:
      type: object
      properties:
        start_time:
          type: string
          example: "2016-07-14T00:00:00Z"
        end_time:
          type: string
          example: "2016-07-14T00:00:00Z"
        duration:
          type: integer
          example: 3
          description: 單位為分鐘
        name:
          type: string
          description: 預警名稱
        type:
          type: string
          description: 預警類型
        field_info:
          $ref: '#/components/schemas/fieldInfo'
        detail:
          oneOf:
            - $ref: '#/components/schemas/rubaseDetail'
            - $ref: '#/components/schemas/alarmDetail'
            - $ref: '#/components/schemas/emptyDetail'
            
        view_logs:
          type: array
          items:
            type: object
            properties:
              time:
                type: string
              account:
                type: string
  examples:
    WarningRealtimeExample:
      value:
        - key: "this-is-key"
          time: "2016-07-14T00:00:00Z"
          name: 預警名稱
          type: rubase-alert
          field_info:
            field: field
            name: 中文名稱
          detail:
            condition:
              time_range:
                start: "00:00:00Z"
                end: "23:59:59Z"
              week_days: [0,1,2,3,4,5,6]
              frequency:
                minutes: 0
                times: 0
              logicals:
                - op: =
                  value: 0
          is_viewed: true
          view_logs:
            - time: "2016-07-14T00:00:00Z"
              account: "account"
        - key: "this-is-key"
          time: "2016-07-14T00:00:00Z"
          name: 告警警名稱
          type: alarm
          field_info:
            field: field
            name: 中文名稱
          detail:
            error_msg: "xxxxx"
          is_viewed: true
          view_logs:
            - time: "2016-07-14T00:00:00Z"
              account: "account"
        - key: "this-is-key2"
          time: "2016-07-14T00:00:00Z"
          name: 欄位斷線
          type: com2scada
          field_info:
            field: field
            name: 中文名稱
          detail:
            msg: "欄位斷線"
          is_viewed: false
          view_logs:
            - time: "2016-07-14T00:00:00Z"
              account: "ppp"
      summary: A sample warning realtime
    WarningListExample:
      value:
        - start_time: "2016-07-14T00:00:00Z"
          end_time: "2016-07-14T00:00:00Z"
          duration: 3
          name: 預警名稱
          type: rubase-alert
          field_info:
            field: field
            name: 中文名稱
          detail:
            condition:
              time_range:
                start: "00:00:00Z"
                end: "23:59:59Z"
              week_days: [0,1,2,3,4,5,6]
              frequency:
                minutes: 0
                times: 0
              logicals:
                - op: =
                  value: 0
          view_logs:
            - time: "2016-07-14T00:00:00Z"
              account: "account"
        - start_time: "2016-07-14T00:00:00Z"
          end_time: "2016-07-14T00:00:00Z"
          duration: 3
          name: 告警警名稱
          type: alarm
          field_info:
            field: field
            name: 中文名稱
          detail:
            error_msg: "xxxxx"
          view_logs:
            - time: "2016-07-14T00:00:00Z"
              account: "account"
        - start_time: "2016-07-14T00:00:00Z"
          end_time: "2016-07-14T00:00:00Z"
          duration: 3
          name: 欄位斷線
          type: com2scada
          field_info:
            field: field
            name: 中文名稱
          detail:
            msg: "欄位斷線"
          view_logs:
            - time: "2016-07-14T00:00:00Z"
              account: "account"
      summary: A sample warning list
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT