openapi: 3.0.0
info:
  version: 1.0.0
  title: Schedule_Service
  description: 預約排程、固定排程及週排程功能服務

paths:
  /v1/scenario/{ID}:
    get:
      tags: [schedule]
      summary: 取得腳本設定清單
      operationId: get-scenario-list
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
          example: 1
          description: element ID
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScenarioOptions'
        '401':
          description: 驗證失敗
        '404':
          description: 資料不存在
        '500':
          description: 伺服器發生錯誤
  /v2/schedule/{NAME}/{TYPE}:
    get:
      tags: [schedule]
      summary: 取得行程詳細
      operationId: get-schedule-detail
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: NAME
          required: true
          schema:
            type: string
          example: A_1F_A105
        - in: path
          name: TYPE
          required: true
          schema:
            type: string
            enum: ["A", "B"]
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScheduleDetail'
        '204':
          description: no content (行程不存在)
        '500':
          description: 伺服器發生錯誤
    post:
      tags: [schedule]
      summary: 建立/更新行程
      operationId: create-schedule
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: NAME
          required: true
          schema:
            type: string
          example: A_1F_A105
        - in: path
          name: TYPE
          required: true
          schema:
            type: string
            enum: ["A", "B"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetScheduleDetail'
      responses:
        '200':
          description: success
        '400':
          description: 無效的輸入
        '500':
          description: 伺服器發生錯誤
  /v1/reservation/{NAME}:
    get:
      tags: [schedule]
      summary: 取得預約排程
      operationId: get-reservation-detail
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: NAME
          required: true
          schema:
            type: string
          example: A_1F_A105
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReservationDetail'
        '204':
          description: no content (行程不存在)
        '500':
          description: 伺服器發生錯誤
    post:
      tags: [schedule]
      summary: 建立預約排程
      operationId: create-reservation
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: NAME
          required: true
          schema:
            type: string
          example: A_1F_A105
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetReservationDetail'
      responses:
        '200':
          description: success
        '400':
          description: 無效的輸入
        '500':
          description: 伺服器發生錯誤
components:
  schemas:
    reversDateTimeAct:
      type: object
      properties:
        time:
          type: string
          description: 執行時間
          example: "2020-09-20T08:00:00+08:00"
        act:
          type: array
          items:
            type: string
          description: 二個模式
          example: ["class", "afterClass"]
      required:
        - time
        - act
    timeAct:
      type: object
      properties:
        time:
          type: string
          description: 開始時間
          example: "08:00:00+08:00"
        act:
          type: array
          items:
            type: string
          description: action key
          example: ["close_light", "open_air_conditioner"]
      required:
        - time
        - act
    intervalAct:
      type: object
      properties:
        start:
          $ref: '#/components/schemas/timeAct'
        end:
          $ref: '#/components/schemas/timeAct'
      required:
        - start
        - end
    GetScenarioOptions:
      type: array
      items:
        type: object
        properties:
          key:
            type: string
          value:
            type: string
        required:
          - key
          - value
    GetReservationDetail:
      type: array
      items:
        $ref: '#/components/schemas/reversDateTimeAct'
    GetScheduleDetail:
      type: object
      properties:
        apply_date:
          type: object
          properties:
            start:
              type: string
              description: 排程適用期間
              example: "2020-09-20T08:00:00+08:00"
            end:
              type: string
              description: 排程適用期間
          required:
            - start
            - end
        mon:
          type: array
          items:
            $ref: '#/components/schemas/intervalAct'
        tue:
          type: array
          items:
            $ref: '#/components/schemas/intervalAct'
        wed:
          type: array
          items:
            $ref: '#/components/schemas/intervalAct'
        thu:
          type: array
          items:
            $ref: '#/components/schemas/intervalAct'
        fri:
          type: array
          items:
            $ref: '#/components/schemas/intervalAct'
        sat:
          type: array
          items:
            $ref: '#/components/schemas/intervalAct'
        sun:
          type: array
          items:
            $ref: '#/components/schemas/intervalAct'
      required:
        - apply_date
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT