services:
  gateway:
    image: devopsfaith/krakend:2.7.2-watch
    labels:
    - traefik.enable=true
    - traefik.http.routers.gateway.rule=Host(`gateway.docker.localhost`)
    - traefik.http.routers.gateway.entrypoints=web
    - traefik.http.services.gateway.loadbalancer.server.port=8000
    - traefik.http.routers.gateway.service=dev-sso-gateway
    - traefik.http.routers.gateway.middlewares=api
    # - traefik.http.routers.dev-sso-gateway.middlewares=oathkeeper, api
    env_file:
    - ./.env.${ENV}
    command: ["run", "-c", "/etc/krakend/krakend.tmpl"]
    volumes:
    - ../:/etc/krakend
    networks:
    - muulin-scada
  # oathkeeper:
  #   image: oryd/oathkeeper:v0.40.7-distroless
  #   depends_on:
  #   - gateway
  #   labels:
  #   - traefik.http.middlewares.oathkeeper.forwardauth.address=http://sso-oathkeeper:4456/decisions
  #   - traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeaders=Authorization
  #   - traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeadersRegex=^X-
  #   command: serve --config=/etc/config/oathkeeper/config-dev.yaml
  #   volumes:
  #     - type: bind
  #       source: ../oathkeeper
  #       target: /etc/config/oathkeeper
  #   restart: on-failure
  #   networks:
  #   - muulin-scada